using System.Collections.Generic;

namespace UnifromEngine
{
    public class Localizations
    {
        public static Dictionary<string, string> RU { get; } = new Dictionary<string, string>()
        {
            { "Key", "Ключ" },
            { "Airhorn", "Гудок" },
            { "LungApparatus", "Батарея" },
            { "BeeHive", "Пчелиный улей" },
            { "GarbageLid", "Крышка от бака" },
            { "BigBolt", "Большой болт" },
            { "BottleBin", "Ящик с пивом" },
            { "Bell", "Колокол" },
            { "Candy", "Конфета" },
            { "CashRegister", "Кассовый аппарат" },
            { "ChemicalJug", "Химический кувшин" },
            { "ClownHorn", "Клоунский гудок" },
            { "Mug", "Кружка кофе" },
            { "Comedy", "Комедия" },
            { "CookieMoldPan", "Форма для печенья" },
            { "DiyFlashbang", "Светошумовая граната" },
            { "DoubleBarrel", "Дробовик" },
            { "ToiletPaperRolls", "Туалетная бумага" },
            { "DustPan", "Совок" },
            { "EasterEgg", "Пасхальное яйцо" },
            { "EggBeater", "Венчик" },
            { "FancyLamp", "Элегантная лампа" },
            { "Flask", "Фляга" },
            { "Cog1", "Шестерня" },
            { "GiftBox", "Подарочная коробка" },
            { "StickyNote", "Записка" },
            { "Clipboard", "Планшет" },
            { "GoldBar", "Золотой слиток" },
            { "FancyCup", "Золотая чаша" },
            { "Brush", "Щетка" },
            { "Clock", "Часы" },
            { "SoccerBall", "Мяч" },
            { "Hairdryer", "Фен" },
            { "PickleJar", "Банка с огурцами" },
            { "KitchenKnife", "Кухонный нож" },
            { "LargeAxle", "Большая ось" },
            { "FlashLaserPointer", "Лазерная указка" },
            { "7Ball", "Магический шар" },
            { "MagnifyingGlass", "Лупа" },
            { "Phone", "Старый телефон" },
            { "FancyPainting", "Картина" },
            { "PerfumeBottle", "Флакон духов" },
            { "PillBottle", "Таблетки" },
            { "FishTestProp", "Пластиковая рыба" },
            { "PlayerBody", "Труп" },
            { "SodaCanRed", "Газировка" },
            { "Remote", "Пульт" },
            { "Ring", "Кольцо" },
            { "RobotToy", "Игрушечный робот" },
            { "RubberDuck", "Уточка" },
            { "SteeringWheel", "Руль" },
            { "StopSign", "Красный знак" },
            { "MetalSheet", "Металлический лист" },
            { "TeaKettle", "Чайник" },
            { "Dentures", "Челюсть" },
            { "MoldPan", "Форма для выпечки" },
            { "Toothpaste", "Зубная паста" },
            { "ToyCube", "Игрушечный кубик" },
            { "ToyTrain", "Игрушечный поезд" },
            { "TragedyMask", "Маска трагедии" },
            { "ComedyMask", "Маска комедии" },
            { "EnginePart1", "Двигатель" },
            { "WhoopieCushion", "Подушка-пердушка" },
            { "YieldSign", "Желтый знак" }
        };
        
        public static Dictionary<string, string> EU { get; } = new Dictionary<string, string>()
        {
            { "Ключ", "Key" },
            { "Гудок", "Airhorn" },
            { "Батарея", "LungApparatus" },
            { "Пчелиный улей", "BeeHive" },
            { "Крышка от бака", "GarbageLid" },
            { "Большой болт", "BigBolt" },
            { "Ящик с пивом", "BottleBin" },
            { "Колокол", "Bell" },
            { "Конфета", "Candy" },
            { "Кассовый аппарат", "CashRegister" },
            { "Химический кувшин", "ChemicalJug" },
            { "Клоунский гудок", "ClownHorn" },
            { "Кружка кофе", "Mug" },
            { "Комедия", "Comedy" },
            { "Форма для печенья", "CookieMoldPan" },
            { "Светошумовая граната", "DiyFlashbang" },
            { "Туалетная бумага", "ToiletPaperRolls" },
            { "Дробовик", "DoubleBarrel" },
            { "Совок", "DustPan" },
            { "Форма для выпечки", "MoldPan" },
            { "Пасхальное яйцо", "EasterEgg" },
            { "Венчик", "EggBeater" },
            { "Элегантная лампа", "FancyLamp" },
            { "Фляга", "Flask" },
            { "Шестерня", "Cog1" },
            { "Подарочная коробка", "GiftBox" },
            { "Записка", "StickyNote" },
            { "Планшет", "Clipboard" },
            { "Золотой слиток", "GoldBar" },
            { "Золотая чаша", "FancyCup" },
            { "Щетка", "Brush" },
            { "Часы", "Clock" },
            { "Мяч", "SoccerBall" },
            { "Фен", "Hairdryer" },
            { "Банка с огурцами", "PickleJar" },
            { "Кухонный нож", "KitchenKnife" },
            { "Большая ось", "LargeAxle" },
            { "Лазерная указка", "FlashLaserPointer" },
            { "Магический шар", "7Ball" },
            { "Лупа", "MagnifyingGlass" },
            { "Старый телефон", "Phone" },
            { "Картина", "FancyPainting" },
            { "Флакон духов", "PerfumeBottle" },
            { "Таблетки", "PillBottle" },
            { "Пластиковая рыба", "FishTestProp" },
            { "Труп", "PlayerBody" },
            { "Газировка", "SodaCanRed" },
            { "Пульт", "Remote" },
            { "Кольцо", "Ring" },
            { "Игрушечный робот", "RobotToy" },
            { "Уточка", "RubberDuck" },
            { "Руль", "SteeringWheel" },
            { "Красный знак", "StopSign" },
            { "Металлический лист", "MetalSheet" },
            { "Чайник", "TeaKettle" },
            { "Челюсть", "Dentures" },
            { "Зубная паста", "Toothpaste" },
            { "Игрушечный кубик", "ToyCube" },
            { "Игрушечный поезд", "ToyTrain" },
            { "Маска трагедии", "TragedyMask" },
            { "Маска комедии", "ComedyMask" },
            { "Двигатель", "EnginePart1" },
            { "Подушка-пердушка", "WhoopieCushion" },
            { "Желтый знак", "YieldSign" }
        };
    }
}